### ISSUE TITLE
Bugs in 1.1

### ISSUE THREAD

**Issue by eagleEggs** [eagleEggs/EHX#8]
1) XPATH's fail to highlight and the elementstore adds up and never deletes itself (this worked in 1.0)
   "ERROR:root:'list' object has no attribute '_parent'"

2) " causes app crash (Possibly other characters need to be validated)
